addon_engine = "EncryptClientEngine"
tx_channels_replacements = [
    [
        "MrpcEngine",
        "EncryptClientEngine",
        0,
        0,
    ],
    [
        "EncryptClientEngine",
        "TcpRpcAdapterEngine",
        0,
        0,
    ],
]
rx_channels_replacements = [
    [
        "TcpRpcAdapterEngine",
        "EncryptClientEngine",
        0,
        0,
    ],
    [
        "EncryptClientEngine",
        "MrpcEngine",
        0,
        0,
    ],
]
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
config_string = '''
'''
