addon_engine = "DelayEngine"
tx_channels_replacements = [
    ["MrpcEngine", "DelayEngine", 0, 0],
    ["DelayEngine", "TcpRpcAdapterEngine", 0, 0],
]
rx_channels_replacements = []
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
config_string = '''
delay_probability = 0.2
delay_ms = 100
'''
