addon_engine = "LoggingEngine"
tx_channels_replacements = [
    ["MrpcEngine", "RateLimitEngine", 0, 0],
    ["RateLimitEngine", "LoggingEngine", 0, 0],
    ["LoggingEngine", "TcpRpcAdapterEngine", 0, 0],
]
rx_channels_replacements = []
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
