addon_engine = "HelloAclEngine"
tx_channels_replacements = [
    [
        "MrpcEngine",
        "HelloAclEngine",
        0,
        0,
    ],
    [
        "HelloAclEngine",
        "TcpRpcAdapterEngine",
        0,
        0,
    ],
]
rx_channels_replacements = [
    [
        "TcpRpcAdapterEngine",
        "HelloAclEngine",
        0,
        0,
    ],
    [
        "HelloAclEngine",
        "MrpcEngine",
        0,
        0,
    ],
]
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
config_string = '''
'''
