addon_engine = "LoggingEngine"
tx_channels_replacements = [
    [
        "RateLimitEngine",
        "LoggingEngine",
        0,
        0,
    ],
    [
        "LoggingEngine",
        "TcpRpcAdapterEngine",
        0,
        0,
    ],
]
rx_channels_replacements = [
    [
        "TcpRpcAdapterEngine",
        "LoggingEngine",
        0,
        0,
    ],
    [
        "LoggingEngine",
        "MrpcEngine",
        0,
        0,
    ],
]
group = ["MrpcEngine", "TcpRpcAdapterEngine", "RateLimitEngine"]
op = "attach"
