addon_engine = "LoggingEngine"
tx_channels_replacements = [
    [
        "RateLimitEngine",
        "LoggingEngine",
        0,
        0,
    ],
    [
        "LoggingEngine",
        "HelloAclSenderEngine",
        0,
        0,
    ],
]
rx_channels_replacements = [
    [
        "HelloAclSenderEngine",
        "LoggingEngine",
        0,
        0,
    ],
    [
        "LoggingEngine",
        "MrpcEngine",
        0,
        0,
    ],
]
group = [
    "MrpcEngine",
    "HelloAclSenderEngine",
    "TcpRpcAdapterEngine",
    "RateLimitEngine",
]
op = "attach"
