addon_engine = "RateLimitEngine"
tx_channels_replacements = [
    [
        "MrpcEngine",
        "RateLimitEngine",
        0,
        0,
    ],
    [
        "RateLimitEngine",
        "HelloAclSenderEngine",
        0,
        0,
    ],
]
rx_channels_replacements = []
group = ["MrpcEngine", "TcpRpcAdapterEngine", "HelloAclSenderEngine"]
op = "attach"
config_string = '''
requests_per_sec = 1000
bucket_size = 1000
'''
